<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        
        <!--
          Revit |  .NET Framework: 
          2014  |  net40
          2015  |  net45
          2016  |  net451
          2017  |  net452
          2018  |  net46
          2019  |  net47
          2020  |  net471
          2021  |  net48
          2022  |  net48
          2023  |  net48
          2024  |  net48
          2025  |  net80
        -->
        
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net48</TargetFramework> <!-- Default .NET Framework -->

        <Configurations>Debug R14;Debug R15;Debug R16;Debug R17;Debug R18;Debug R19;Debug R20;Debug R21;Debug R22;Debug R23;Debug R24;Debug R25</Configurations>
        <Configurations>$(Configurations);Release R14;Release R15;Release R16;Release R17;Release R18;Release R19;Release R20;Release R21;Release R22;Release R23;Release R24;Release R25</Configurations>
        
        <!-- Define handy symbols to use in the code in order to accommodate different Revit versions,
  e.g. by wrapping legacy / deprecated API calls with #if REVIT2014 | REVIT2015 -->
        <DefineConstants>REVIT$(RevitVersion);WINFORMS</DefineConstants>
        <PreprocessorDefinitions>$(DefineConstants)</PreprocessorDefinitions>
        
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('R14'))">
        <RevitVersion>2014</RevitVersion>
        <TargetFramework>net40</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R15'))">
        <RevitVersion>2015</RevitVersion>
        <TargetFramework>net45</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R16'))">
        <RevitVersion>2016</RevitVersion>
        <TargetFramework>net451</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R17'))">
        <RevitVersion>2017</RevitVersion>
        <TargetFramework>net452</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R18'))">
        <RevitVersion>2018</RevitVersion>
        <TargetFramework>net46</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R19'))">
        <RevitVersion>2019</RevitVersion>
        <TargetFramework>net47</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R20'))">
        <RevitVersion>2020</RevitVersion>
        <TargetFramework>net471</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R21'))">
        <RevitVersion>2021</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R22'))">
        <RevitVersion>2022</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R23'))">
        <RevitVersion>2023</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R24'))">
        <RevitVersion>2024</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R25'))">
        <RevitVersion>2025</RevitVersion>
        <TargetFramework>net80</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autodesk.Revit.SDK" Version="2025.*" Condition="'$(RevitVersion)' == '2025'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2024.*" Condition="'$(RevitVersion)' == '2024'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2023.*" Condition="'$(RevitVersion)' == '2023'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2022.*" Condition="'$(RevitVersion)' == '2022'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2021.*" Condition="'$(RevitVersion)' == '2021'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2020.*" Condition="'$(RevitVersion)' == '2020'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2019.*" Condition="'$(RevitVersion)' == '2019'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2018.*" Condition="'$(RevitVersion)' == '2018'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2017.*" Condition="'$(RevitVersion)' == '2017'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2016.*" Condition="'$(RevitVersion)' == '2016'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2015.*" Condition="'$(RevitVersion)' == '2015'" PrivateAssets="All" />
        <PackageReference Include="Autodesk.Revit.SDK" Version="2014.*" Condition="'$(RevitVersion)' == '2014'" PrivateAssets="All" />
    </ItemGroup>
    
</Project>
