<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autodesk.Revit.SDK" Version="2025.0.2.419" />
      <PackageReference Include="ZstdSharp.Port" Version="0.8.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\RevitAddinMultiVersionR14.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR14.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR15.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR15.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR16.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR16.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR17.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR17.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR18.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR18.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR19.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR19.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR20.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR20.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR21.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR21.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR22.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR22.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR23.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR23.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR24.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR24.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="Resources\RevitAddinMultiVersionR25.zstd" />
      <Resource Include="Resources\RevitAddinMultiVersionR25.zstd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

</Project>
